// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StokTakipSistemi.Data;

#nullable disable

namespace StokTakipSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724140648_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StokTakipSistemi.Entities.Depo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lokasyon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Depolar");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.DepoStok", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("depo_id")
                        .HasColumnType("int");

                    b.Property<decimal>("miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("urun_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("DepoStoklari");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Kullanici", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kullanici_adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("kullanici_durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("rol_id")
                        .HasColumnType("int");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Transfer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cikis_depo_id")
                        .HasColumnType("int");

                    b.Property<string>("fis_numarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("varis_depo_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Transferler");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.TransferDetay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("transfer_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urun_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TransferDetaylari");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Urun", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("birim")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("urun_adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("urun_kodu")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
