// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StokTakipSistemi.Data;

#nullable disable

namespace StokTakipSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729091436_iliskiler")]
    partial class iliskiler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StokTakipSistemi.Entities.Depo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lokasyon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("olusturan_kullanici_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("olusturan_kullanici_id");

                    b.ToTable("Depolar");

                    b.HasData(
                        new
                        {
                            id = 1,
                            ad = "Ana Depo",
                            lokasyon = "Merkez",
                            olusturan_kullanici_id = 0,
                            olusturulma_zamani = new DateTime(2026, 7, 29, 12, 14, 36, 403, DateTimeKind.Local).AddTicks(4882)
                        });
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.DepoStok", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("depo_id")
                        .HasColumnType("int");

                    b.Property<decimal>("miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("olusturan_kullanici_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("urun_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("depo_id");

                    b.HasIndex("olusturan_kullanici_id");

                    b.HasIndex("urun_id");

                    b.ToTable("DepoStoklari");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Kullanici", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kullanici_adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("kullanici_durum")
                        .HasColumnType("bit");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("rol_id")
                        .HasColumnType("int");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("rol_id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            id = 1,
                            ad = "Yonetici",
                            kullanici_adi = "admin",
                            kullanici_durum = true,
                            olusturulma_zamani = new DateTime(2026, 7, 29, 12, 14, 36, 403, DateTimeKind.Local).AddTicks(4865),
                            rol_id = 1,
                            sifre = "123456",
                            soyad = "Hesap"
                        });
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Rol", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Roller");

                    b.HasData(
                        new
                        {
                            id = 1,
                            adi = "Admin",
                            olusturulma_zamani = new DateTime(2026, 7, 29, 12, 14, 36, 403, DateTimeKind.Local).AddTicks(4763)
                        },
                        new
                        {
                            id = 2,
                            adi = "Personel",
                            olusturulma_zamani = new DateTime(2026, 7, 29, 12, 14, 36, 403, DateTimeKind.Local).AddTicks(4772)
                        });
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Transfer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cikis_depo_id")
                        .HasColumnType("int");

                    b.Property<string>("fis_numarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("transfer_kullanici_id")
                        .HasColumnType("int");

                    b.Property<int>("varis_depo_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("cikis_depo_id");

                    b.HasIndex("transfer_kullanici_id");

                    b.HasIndex("varis_depo_id");

                    b.ToTable("Transferler");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.TransferDetay", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("miktar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.Property<int>("transfer_id")
                        .HasColumnType("int");

                    b.Property<int>("urun_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("transfer_id");

                    b.HasIndex("urun_id");

                    b.ToTable("TransferDetaylari");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Urun", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("birim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ekleyen_kullanici_id")
                        .HasColumnType("int");

                    b.Property<decimal>("kdv")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("olusturulma_zamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("urun_adi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("urun_kodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("ekleyen_kullanici_id");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Depo", b =>
                {
                    b.HasOne("StokTakipSistemi.Entities.Kullanici", "olusturan_kullanici")
                        .WithMany()
                        .HasForeignKey("olusturan_kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("olusturan_kullanici");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.DepoStok", b =>
                {
                    b.HasOne("StokTakipSistemi.Entities.Depo", "depo")
                        .WithMany()
                        .HasForeignKey("depo_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokTakipSistemi.Entities.Kullanici", "olusturan_kullanici")
                        .WithMany()
                        .HasForeignKey("olusturan_kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokTakipSistemi.Entities.Urun", "urun")
                        .WithMany()
                        .HasForeignKey("urun_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("depo");

                    b.Navigation("olusturan_kullanici");

                    b.Navigation("urun");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Kullanici", b =>
                {
                    b.HasOne("StokTakipSistemi.Entities.Rol", "rol")
                        .WithMany()
                        .HasForeignKey("rol_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("rol");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Transfer", b =>
                {
                    b.HasOne("StokTakipSistemi.Entities.Depo", "cikis_depo")
                        .WithMany()
                        .HasForeignKey("cikis_depo_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StokTakipSistemi.Entities.Kullanici", "transfer_kullanici")
                        .WithMany()
                        .HasForeignKey("transfer_kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokTakipSistemi.Entities.Depo", "varis_depo")
                        .WithMany()
                        .HasForeignKey("varis_depo_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("cikis_depo");

                    b.Navigation("transfer_kullanici");

                    b.Navigation("varis_depo");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.TransferDetay", b =>
                {
                    b.HasOne("StokTakipSistemi.Entities.Transfer", "transfer")
                        .WithMany()
                        .HasForeignKey("transfer_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StokTakipSistemi.Entities.Urun", "urun")
                        .WithMany()
                        .HasForeignKey("urun_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("transfer");

                    b.Navigation("urun");
                });

            modelBuilder.Entity("StokTakipSistemi.Entities.Urun", b =>
                {
                    b.HasOne("StokTakipSistemi.Entities.Kullanici", "ekleyen_kullanici")
                        .WithMany()
                        .HasForeignKey("ekleyen_kullanici_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ekleyen_kullanici");
                });
#pragma warning restore 612, 618
        }
    }
}
